ALTER TABLE public.arquivo DROP COLUMN dados;
ALTER TABLE public.arquivo ADD dados BYTEA NOT NULL;
INSERT INTO public.perfil(id_perfil, nome) VALUES (nextval('perfil_seq'), 'ADM');
INSERT INTO public.usuario(id_usuario, email, login, nome, senha) VALUES (nextval('usuario_seq'), 'gustavo@codersistemas.com.br', 'gustavo', 'Gustavo da Silva', '123');
INSERT INTO public.usuario_perfil(id_usuario, id_perfil) VALUES (1, 1);
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (50, 'Deletronicos', '001.000.000.000', 'Eletrônicos');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (51, 'Eletrodomésticos', '002.000.000.000', 'Eletrodomésticos');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (52, 'Automotivo', '003.000.000.000', 'Automotivo');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (53, 'Celulares', '001.002.000.000', 'Celulares');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (54, 'Informática', '001.001.000.000', 'Informática');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (55, 'Notebook', '001.001.001.000', 'Notebook');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (56, 'Desktops', '001.001.002.000', 'Desktops');
INSERT INTO departamento (id_departamento, descricao, estrutura, nome) VALUES (57, 'Peças e acessórios', '001.001.003.000', 'Peças e acessórios');
SELECT pg_catalog.setval('departamento_seq', 1, true);
INSERT INTO fabricante (id_fabricante, nome) VALUES (50, 'Motorolla');
INSERT INTO fabricante (id_fabricante, nome) VALUES (51, 'LG Eletronics');
SELECT pg_catalog.setval('fabricante_seq', 1, true);
INSERT INTO valor (id_valor, ativo, dt_fim, dt_inicio, valor, id_produto) VALUES (50, true, '2020-12-31', '2000-01-01', 1500.00, null);
INSERT INTO produto (id_produto, ativo, cod_referencia_fabricante, descricao, nome, id_departamento, id_fabricante, id_valor) VALUES (50, true, 'weqwewq', 'Celular bom', 'Moto G4 Plus', 53, 50, 50);
UPDATE VALOR SET ID_PRODUTO = 50;
INSERT INTO caracteristica_produto (id_caracteristica_produto, tipo, valor, id_produto) VALUES (50, 'Tamanho Tela', '5 polegadas', 50);
INSERT INTO caracteristica_produto (id_caracteristica_produto, tipo, valor, id_produto) VALUES (51, 'Tipo de rede', '4G', 50);
